services:
  - type: web
    name: norma-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt gunicorn gevent
    startCommand: gunicorn -c gunicorn_config.py wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: norma-db
          property: connectionString

databases:
  - name: norma-db
    databaseName: norma
    ipAllowList: []
